### ISSUE TITLE
Mojave won't open

### ISSUE THREAD

**Issue by caiohen** [thedzy/Run-script-as-an-Applicaiton#1]
Hello, i've found this code by searching for an easy way to turn `.sh` into `.app` files.

I am currently using the new Mojave 10.14 and when I try to run the application it just don't execute.
I double click on the icon and nothing happens. It don't even open the Terminal with some debug `echo` tests.

Is it suppose to perform like this?
Thanks.

**Comment by rredpoppy** [comment]
if the behavior is that in terminal you get an error like `LSOpenURLsWithRole() failed with error -10810`.. then you need to chmod +x for the script file: `chmod +x ./Script-sh.app/Contents/MacOS/main.command`

**Comment by manaleak** [comment]
I use Mac OS Catalina and unfortunately for me it's the same. Also changing the permission doesn't help.

**Comment by thedzy** [comment]
To verify this works, I ran sudo chmod a-rwx from the Script-sh.app which effectively kills it.
For testing I put in the script:
    echo test > $HOME/Downlaods/test.txt

Then I added read permission with sticky bit to everything in the app
    sudo chmod -R a+rX  Script-sh.app/
Added execute to the script for everyone:
    sudo chmod a+x Script-sh.app/Contents/MacOS/main.command
Shouldn't make a difference but you can add execute to the app for everyone:
    sudo chmod a+x Script-sh.app/

Verified in Catalina 10.15.5

Can you verify?  It's possible you are missing a read permission.
